{
 "title": "Service Dashboard",
 "time": { "from": "2024-10-03T18:54:34.292Z", "to": "2024-10-03T18:58:08.166Z" },
 "panels": [
  {
   "title": "Общее количество успешных запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "service_service_http_requests_total{job=\"fastapi\", status=~\"200|201\", handler!=\"/metrics\"}",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Теущая нагрузка на сервис",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(service_service_http_requests_total{job=\"fastapi\", handler!=\"/metrics\"})",
     "legendFormat": "Количество запросов на сервис"
    }
   ]
  },
  {
   "title": "Среднее время ответа",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(service_service_http_request_duration_seconds_sum{handler!=\"/metrics\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(service_service_http_requests_total{handler!=\"/metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество HTTP ошибок по кодам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "service_service_http_requests_total{status!=\"200\", status!=\"307\", status!=\"201\"}",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}